---
- id: packer-validate
  name: Packer validate
  description: Checks packer template is valid.
  entry: hooks/packer_validate.sh
  language: script
  files: (\.pkr\.hcl)$
  always_run: false

- id: packer-fmt
  name: Packer fmt
  description: Rewrites HCL2 config files to canonical format.
  entry: hooks/packer_fmt.sh
  language: script
  files: (\.pkr\.hcl)$
  always_run: false
